-- INSERT INTO WINES VALUES (1, "Rooiberg", "Pinotage", "South Africa");
-- INSERT INTO WINES VALUES (2, "KWV", "Shiraz", "South Africa");
-- INSERT INTO WINES VALUES (3, "Marks & Spencer", "Pinot Noir", "France");
